services:
  app:
    hostname: example
    image: civicrm/wordpress:latest
    ports:
      - 8760:80 # CiviCRM will be available on port 8760.
    restart: unless-stopped
    volumes:
      - uploads:/var/www/html/wp-content/uploads
    environment:
      # db info
      # CIVICRM_DSN: mysql://civicrm:${MYSQL_PASSWORD}@db:3306/civicrm # Note: you can also pass database credentials as a DSN.
      CIVICRM_DB_HOST: db
      CIVICRM_DB_PORT: 3306
      CIVICRM_DB_NAME: civicrm
      CIVICRM_DB_USER: civicrm
      CIVICRM_DB_PASSWORD: ${MYSQL_PASSWORD}
      # CiviCRM info
      CIVICRM_UF_BASEURL: http://localhost:8760
      # WordPress info
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_SITE_TITLE: example-site
      CIVICRM_ADMIN_EMAIL: admin@example.com
  db:
    hostname: db
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: civicrm
      MYSQL_USER: civicrm
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
volumes:
  uploads:
  db:
